steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
      dir: 'functions/autodeploy'
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['functions', 'deploy', 'cloud-fn-cicdnode', '--trigger-http', '--runtime', 'nodejs10', '--entry-point', 'sayhello']
      dir: 'functions/autodeploy'